name: Juan Benet
url: http://juan.benet.ai
description: Juan Benet's Website
github: jbenet
markdown: redcarpet
#markdown: kramdown
redcarpet:
  extensions: [with_toc_data, footnotes]
permalink: /:categories/:year-:month-:day/:title
highlighter: rouge
category_dir: "."
category_title_prefix: ""
